name: Publish

on:
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: [ubuntu-latest]

        steps:
            - uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: '14.x'

            - name: installing dependencies
              run: yarn install

            - name: semantic release
              run: yarn run semantic-release
              env:
                  CI: true
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
